{% set name = "whisper" %}
{% set version = "1.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/whisper-{{ version }}.tar.gz
  sha256: 435b4fb843c4c752719bdf0511a652d5be710e9bb35ad9ebe3b133268ee31c44
build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - six

test:
  imports:
    - whisper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://graphiteapp.org
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: File-based time-series database format for Graphite
  description: |
    Whisper is a fixed-size database, similar in design and purpose to RRD
    (round-robin-database). It provides fast, reliable storage of numeric data
    over time. Whisper allows for higher resolution (seconds per point) of
    recent data to degrade into lower resolutions for long-term retention of
    historical data.
  doc_url: https://graphite.readthedocs.io/
  dev_url: https://github.com/graphite-project/whisper
